

num_waypoints: 5

# scenario_num:
# 0: random selection
# 1: head on
# 2: overtaking
# 3: overtaken
# 4: crossing give way
# 5: crossing stand on
# 6: multi-ship
scenario_num: 0
os_max_speed: 20
ts_max_speed: 20
num_ships: 3
