type: 1
n_ships: 5
min_dist_between_ships: 50.0
ship_list:
  - guidance:
      ktp:
        epsilon: 0.0001
        dt_seg: 0.1
    controller:
      pid:
        wn: [0.3, 0.3, 0.3]
        zeta: [1.0, 1.0, 1.0]
        eta_diff_max: [100.0, 100.0, 1.57]
    model:
      telemetron: ''
  - guidance:
      ktp:
        epsilon: 0.0001
        dt_seg: 0.1
    controller:
      pid:
        wn: [0.3, 0.3, 0.3]
        zeta: [1.0, 1.0, 1.0]
        eta_diff_max: [100.0, 100.0, 1.57]
    model:
      telemetron: ''