type: 1
n_ships: 1
min_dist_between_ships: 500.0
max_dist_between_ships: 1000.0
ship_list:
  - default: ''
  - tracker:
      kf:
        P_0: [25.1, 25.1, 0.11, 0.11]
        q: 0.02
    sensors:
      - radar:
          measurement_rate: 0.55
          R: [25.3, 25.3]
      - ais:
          ais_class: 0
          R: [26.3, 26.3]
    guidance:
      los:
        pass_angle_threshold: 80.0
        R_a: 15.0
        K_p: 0.024
        K_i: 0.0
        e_int_max: 101.0
    controller:
      flsh:
        K_p_u: 5.1
        K_p_psi: 6.1
        K_d_psi: 12.1
    model:
      telemetron: ''
  - tracker:
      kf:
        P_0: [25.1, 25.1, 0.11, 0.11]
        q: 0.02
    sensors:
      - radar:
          measurement_rate: 0.55
          R: [25.3, 25.3]
      - ais:
          ais_class: 0
          R: [26.3, 26.3]
    guidance:
      los:
        pass_angle_threshold: 90.0
        R_a: 15.0
        K_p: 0.025
        K_i: 0.0
        e_int_max: 100.0
    controller:
      pass_through_cs: ''
    model:
      csog:
        draft: 2.5
        length: 10.5
        width: 3.5
        T_chi: 3.0
        T_U: 5.0
        r_max: 9.0
        U_min: 0.0
        U_max: 15.0
  - tracker:
      kf:
        P_0: [25.1, 25.1, 0.11, 0.11]
        q: 0.02
    sensors:
      - radar:
          measurement_rate: 0.55
          R: [25.3, 25.3]
      - ais:
          ais_class: 0
          R: [26.3, 26.3]
    guidance:
      ktp:
        epsilon: 0.000001
        dt_seg: 0.1
    controller:
      pid:
        wn: [0.3, 0.1, 0.3]
        zeta: [1.0, 1.0, 1.0]
        eta_diff_max: [110.0, 110.0, 1.9]
    model:
      telemetron: ''
  - tracker:
      kf:
        P_0: [25.1, 25.1, 0.11, 0.11]
        q: 0.02
    sensors:
      - radar:
          measurement_rate: 0.55
          R: [25.3, 25.3]
      - ais:
          ais_class: 0
          R: [26.3, 26.3]
    guidance:
      ktp:
        epsilon: 0.000001
        dt_seg: 0.11
    controller:
      pid:
        wn: [0.3, 0.3, 0.4]
        zeta: [1.0, 1.0, 1.0]
        eta_diff_max: [100.0, 100.0, 1.57]
    model:
      telemetron: ''
