
n_ship_range: [1, 10]
n_wps_range: [6, 15]
speed_plan_variation_range: [-1.0, 1.0]
waypoint_dist_range: [500.0, 10000.0]
waypoint_ang_range: [-45.0, 45.0]
ho_bearing_range: [-20.0, 20.0]
ho_heading_range: [-15.0, 15.0]
ot_bearing_range: [-20.0, 20.0]
ot_heading_range: [-15.0, 15.0]
cr_bearing_range: [15.1, 112.5]
cr_heading_range: [-15.0, 15.0]
dist_between_ships_range: [300.0, 10000.0]
