ship0: #own-ship
  ship_model: telemetron
  radar_active: True
  radar_meas_rate: 2
  radar_sigma_z: 2

  ais_active: True
  ais_meas_rate: 4
  ais_sigma_z: 2
  ais_loss_prob: 0.0

  #LOS guidance parameters
  lookahead_distance: 100
  radius_of_acceptance: 50

ship1:
  ship_model: telemetron

  radar_active: True
  radar_meas_rate: 2
  radar_sigma_z: 2

  ais_active: True
  ais_meas_rate: 4
  ais_sigma_z: 2
  ais_loss_prob: 0.0

  #LOS guidance parameters
  lookahead_distance: 100
  radius_of_acceptance: 50

default:
  ship_model: random
  radar_active: True
  radar_meas_rate: 2
  radar_sigma_z: 2

  ais_active: True
  ais_meas_rate: 4
  ais_sigma_z: 2
  ais_loss_prob: 0.0

  #LOS guidance parameters
  lookahead_distance: 100
  radius_of_acceptance: 50
