t_start: 0.0
dt_sim: 0.1
t_end: 300.0
scenario_files: ["head_on.yaml"]
save_scenario_results: True
visualize: False
verbose: True
ais_data_column_format: ["mmsi", "lon", "lat", "date_time_utc", "sog", "cog", "true_heading", "nav_status", "message_nr", "source"]