t_start: 1000.0
dt_sim: 2.0
t_end: 2000.0
scenario_files: ["head_on.yaml"]
save_animation: True
visualize: True
verbose: True
ais_data_column_format: ["mmsi", "lon", "lat", "date_time_utc", "sog", "cog", "true_heading", "nav_status", "message_nr", "source"]