#scenario_files: ["head_on.yaml", "crossing_give_way.yaml", "crossing_stand_on.yaml", "overtaking.yaml", "overtaken.yaml"]
#scenario_files: ["crossing_stand_on.yaml"]
#scenario_files: ["aalesund_random.yaml"]
scenario_files: ["aalesund_random_20012023_13_00_55.yaml"]
#scenario_files: ["aalesund_random_18012023_13_48_46.yaml"]
save_scenario_results: True
visualize: True
verbose: True
ais_data_column_format: ["mmsi", "lon", "lat", "date_time_utc", "sog", "cog", "true_heading", "nav_status", "message_nr", "source"]