t_start: 0.0
dt_sim: 1.0
t_end: 3000.0
scenario_files: ["ais_scenario.yaml", "head_on.yaml"]
save_scenario_results: True
visualize: True
verbose: True
ais_data_column_format: ["mmsi", "lon", "lat", "date_time_utc", "sog", "cog", "true_heading", "nav_status", "message_nr", "source"]