save_scenario_results: False
verbose: True
visualizer:
  show_liveplot: True
  show_colav_results_live: True
  show_measurements: False
  show_liveplot_tracks: True
  show_waypoints: True
  zoom_in_liveplot_on_ownship: True
  zoom_window_width: 1000.0
  show_results: True
  show_target_tracking_results: True
  show_trajectory_tracking_results: True
  save_result_figures: False
  save_liveplot_animation: False
  dark_mode_liveplot: True
  update_rate_liveplot: 1.0 # relative to simulation time, not wall
  figsize: [12, 10]
  margins: [0.0, 0.0]
  ship_linewidth: 1.7
  ship_scaling: [1.0, 1.0]
  ship_info_fontsize: 10
  ship_colors: ["xkcd:black",
              "xkcd:red",
              "xkcd:eggshell",
              "xkcd:purple",
              "xkcd:cyan",
              "xkcd:orange",
              "xkcd:fuchsia",
              "xkcd:yellow",
              "xkcd:grey",
              "xkcd:reddish brown",
              "xkcd:bubblegum",
              "xkcd:baby shit brown",
              "xkcd:khaki",
              "xkcd:cloudy blue",
              "xkcd:pale aqua",
              "xkcd:light lilac",
              "xkcd:lemon",
              "xkcd:powder blue",
              "xkcd:wine",
              "xkcd:amber",
              "xkcd:wheat"]
  do_linewidth: 1.7
  do_colors: ["xkcd:light red",
              "xkcd:pale lilac",
              "xkcd:aqua",
              "xkcd:peach",
              "xkcd:pale purple",
              "xkcd:goldenrod",
              "xkcd:light grey",
              "xkcd:wine",
              "xkcd:amber",
              "xkcd:wheat",
              "xkcd:burnt sienna",
              "xkcd:barbie pink",
              "xkcd:ugly brown",
              "xkcd:light tan",
              "xkcd:stormy blue",
              "xkcd:light aquamarine",
              "xkcd:lemon",
              "xkcd:pastel blue",
              "xkcd:blue green",
              "xkcd:eggshell",
              "xkcd:purple",
              "xkcd:cyan",
              "xkcd:orange",
              "xkcd:fuchsia"
          ]


