t_start: 0.0
dt_sim: 0.1
t_end: 100.0
scenario_files: ["new_scenario"]
save_animation: True
show_animation: True
show_waypoints: True
verbose: True
ais_data_column_format: ["mmsi", "lon", "lat", "datetime_utc", "sog", "cog", "true_heading", "nav_status", "message_nr", "source"]