
save_animation: False
show_animation: True
show_waypoints: True

frame_delay: 100 # in milliseconds

figsize: [14, 10]
linewidth: 2.1
margins: [0.00, 0.00]

ship_colors: ["xkcd:black", "xkcd:red", "xkcd:green", "xkcd:cyan", "xkcd:orange", "xkcd:fuchsia", "xkcd:yellow", "xkcd:grey", "xkcd:reddish brown", "xkcd:bubblegum", "xkcd:baby shit brown", "xkcd:eggshell", "xkcd:cloudy blue", "xkcd:pale aqua", "xkcd:light lilac", "xkcd:dark forest green", "xkcd:powder blue"]