show_liveplot: False
show_results: True
show_measurements: False
show_tracks: False
show_animation: False
show_waypoints: True
save_animation: False

frame_delay: 10 # in milliseconds

figsize: [14, 10]
margins: [0.0, 0.0]
ship_linewidth: 1.7
ship_scaling: [10.0, 14.0]
ship_info_fontsize: 10
ship_colors: ["xkcd:black",
            "xkcd:red",
            "xkcd:eggshell",
            "xkcd:purple",
            "xkcd:cyan",
            "xkcd:orange",
            "xkcd:fuchsia",
            "xkcd:yellow",
            "xkcd:grey",
            "xkcd:reddish brown",
            "xkcd:bubblegum",
            "xkcd:baby shit brown",
            "xkcd:khaki",
            "xkcd:cloudy blue",
            "xkcd:pale aqua",
            "xkcd:light lilac",
            "xkcd:lemon",
            "xkcd:powder blue",
            "xkcd:wine",
            "xkcd:amber",
            "xkcd:wheat"]
do_linewidth: 1.7
do_colors: ["xkcd:light red",
            "xkcd:pale lilac",
            "xkcd:aqua",
            "xkcd:peach",
            "xkcd:pale purple",
            "xkcd:goldenrod",
            "xkcd:light grey",
            "xkcd:wine",
            "xkcd:amber",
            "xkcd:wheat",
            "xkcd:burnt sienna",
            "xkcd:barbie pink",
            "xkcd:ugly brown",
            "xkcd:light tan",
            "xkcd:stormy blue",
            "xkcd:light aquamarine",
            "xkcd:lemon",
            "xkcd:pastel blue",
            "xkcd:blue green",
            "xkcd:eggshell",
            "xkcd:purple",
            "xkcd:cyan",
            "xkcd:orange",
            "xkcd:fuchsia"
        ]